#!/bin/bash
while read line
do
  generation=$(echo "$line" | cut -f2 -d=)
  mosquitto_pub -h "${MQTT_HOST}" -t meters/turbine/total_generation -m $generation -r
  echo "$(date -Iseconds): meters/turbine/total_generation: $generation"
done < /dev/stdin
